sudo: false
dist: trusty

language: cpp

os:
  - linux
  - osx

osx_image: xcode10

cache:
  directories:
  - posix/src
  - xcode/src

env:
  global:
    - MAKEFLAGS="-j 2"

compiler:
  - gcc
  # - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-4.0
    packages:
    - libtool
    - gcc-4.9
    - g++-4.9
    - clang-4.0
    - libgtk2.0-dev
    - libxml2-dev
    - uuid-dev
  homebrew:
    packages:
    - libtool

install:
  - if [ "$TRAVIS_OS_NAME" = linux -a "$CXX" = "g++" ]; then export CC="gcc-4.9" CXX="g++-4.9" CFLAGS="-g0 -O0" CXXFLAGS="-g0 -O0"; fi
  - if [ "$TRAVIS_OS_NAME" = linux -a "$CXX" = "clang++" ]; then export CC="clang-4.0" CXX="clang++-4.0" CFLAGS="-g0 -O0" CXXFLAGS="-g0 -O0"; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then cd posix; else cd xcode; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then echo "PKG_CONFIG = /usr/local/bin/pkg-config" > config.mk; fi
  - make -s download
  - travis_wait 60 make -s external
  - make -s all

script:
  - if [ "$TRAVIS_OS_NAME" = linux ]; then make check; else make; fi # in posix/ or xcode/
