language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - libtool
    - gcc-4.8
    - g++-4.8
    - clang-3.7

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install pkg-config; fi

install:
  - if [ "$TRAVIS_OS_NAME" = linux -a "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$TRAVIS_OS_NAME" = linux -a "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then cd posix; else cd xcode; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then echo "PKG_CONFIG = /usr/local/bin/pkg-config" > config.mk; fi
  - make -s

script: make check # in posix/ or xcode/
