dist: xenial

language: cpp

os:
  - linux
  - osx

osx_image: xcode10.2

cache:
  directories:
  - posix/src
  - xcode/src

env:
  global:
    - MAKEFLAGS="-j 2"

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libgtk2.0-dev
    - libsqlite3-dev
    - uuid-dev
  homebrew:
    packages:
    - libtool

install:
  - if [ "$TRAVIS_OS_NAME" = linux -a "$CXX" = "g++" ]; then export CFLAGS="-g0 -O0" CXXFLAGS="-g0 -O0"; fi
  - if [ "$TRAVIS_OS_NAME" = linux -a "$CXX" = "clang++" ]; then export CFLAGS="-g0 -O0" CXXFLAGS="-g0 -O0"; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then cd posix; else cd xcode; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then echo "PKG_CONFIG = /usr/local/bin/pkg-config" > config.mk; fi
  - make -s download
  - travis_wait 60 make -s external
  - make -s all

script:
  - make check # in posix/ or xcode/
